spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
      username: resdb
      password: ENC(LwpHSjmwXgVYHjU1M9aZuA==)
      type: com.alibaba.druid.pool.DruidDataSource
  cache:
    jcache:
      config: ehcache3.xml
  thymeleaf:
      cache: false
      mode: LEGACYHTML5
#日志配置
logging:
  config: classpath:logback-spring.xml

#mybatis相关配置
mybatis:
    type-aliases-package: com.cupdata.sip.common.dao.entity
    mapper-locations: com/cupdata/sip/common/dao/mapping/*.xml
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL
    before: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
#配置Hystrix的超时时间为5秒，解决Feign/Ribbon第一次请求失败的问题
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  eager-load:
    enabled: true

jasypt:
  encryptor:
    password: cupdata

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:46960/eureka/   #设置与Eureka Server交互的地址，多个地址之间逗号分割
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true     #表示将ip注册到Eureka server