spring:
  application:
    name: api-gateway
server:
   port: 8040         # 指定该实例的端口
eureka:
  client:
    registerWithEureka: true  #false:不作为一个客户端注册到注册中心
    fetchRegistry: true      #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
   hostname: localhost    # 指定该Eureka实例的主机名
   lease-expiration-duration-in-seconds: 6
   lease-renewal-interval-in-seconds: 2

# zuul 网关配置
zuul:
  #prefix: /api
  routes:
    trvok-service:                  # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /trvok/**               # 想要映射到的路径
      service-id: trvok-service     # Eureka中的serviceId
    voucher-service:
      path: /voucher/**
      service-id: voucher-service
