spring:
  application:
    name: cdd-service
  profiles:
    active: test
    
server:
   port: 46983         # 指定该实例的端口
   
#日志配置
logging:
  config: classpath:logback-spring.xml

#配置Hystrix的超时时间为5秒，解决Feign/Ribbon第一次请求失败的问题
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

--- # 开发环境**********************************************************************************************************
spring:
  profiles: dev

eureka:
  client:
    registerWithEureka: false    #是否将自己注册到Eureka Server，因为当前应用就是Eureka Server，所以设置为false
    fetchRegistry: false         #是否从Eureka Server获取注册信息，因为为单点，所以设置为false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:46960/eureka/   #设置与Eureka Server交互的地址，多个地址之间逗号分割
  instance:
    hostname: localhost    # 指定该Eureka实例的主机名               
            
--- # 测试环境**********************************************************************************************************
spring:
  profiles: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.193.17.84:46960/eureka/,http://10.193.17.86:46960/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 20

--- # 生产环境**********************************************************************************************************
spring:
  profiles: prd
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.150.9.20:46960/eureka/,http://10.150.9.21:46960/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 20
