spring:
  application:
    name: ihuyi-service
server:
  port: 9030

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost         # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 2

