spring:
  application:
    name: order-service
  profiles:
    active: test
server:
   port: 46964         # 指定该实例的端口
#mybatis相关配置
mybatis:
    type-aliases-package: com.cupdata.commons.model
    mapper-locations: classpath:mapper/*.xml

#配置Hystrix的超时时间为10秒，解决Feign/Ribbon第一次请求失败的问题
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
#日志配置
logging:
  config: classpath:logback-spring.xml

--- # 测试环境**********************************************************************************************************
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
    username: resdb
    password: resdb
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http:10.193.17.84:46960/eureka/,http:10.193.17.86:46960/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 20


--- # 生产环境**********************************************************************************************************
spring:
  profiles: prd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
    username: resdb
    password: resdb
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http:10.193.17.84:46960/eureka/,http:10.193.17.86:46960/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 20