spring:
  application:
    name: order-service
  profiles:
    active: dev
server:
   port: 46964         # 指定该实例的端口
#mybatis相关配置
mybatis:
    type-aliases-package: com.cupdata.commons.model
    mapper-locations: classpath:mapper/*.xml

#配置Hystrix的超时时间为10秒，解决Feign/Ribbon第一次请求失败的问题
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
#日志配置
logging:
  config: classpath:logback-spring.xml

jasypt:
  encryptor:
    password: cupdata

--- # 开发环境**********************************************************************************************************
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
    username: resdb
    password: ENC(LwpHSjmwXgVYHjU1M9aZuA==)
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    registerWithEureka: false    #是否将自己注册到Eureka Server，因为当前应用就是Eureka Server，所以设置为false
    fetchRegistry: false         #是否从Eureka Server获取注册信息，因为为单点，所以设置为false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:46960/eureka/   #设置与Eureka Server交互的地址，多个地址之间逗号分割
  instance:
    hostname: localhost    # 指定该Eureka实例的主机名

--- # 测试环境**********************************************************************************************************
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
    username: resdb
    password: ENC(LwpHSjmwXgVYHjU1M9aZuA==)
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.193.17.84:46960/eureka/,http://10.193.17.86:46960/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 20


--- # 生产环境**********************************************************************************************************
spring:
  profiles: prd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.150.9.22:3306/sip?useUnicode=true&characterEncoding=UTF-8
    username: sip
    password: ENC(7eaGzJhB0t+ZjmzjELKw0QjoNwE573Mr)
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.150.9.20:46960/eureka/,http://10.150.9.21:46960/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 20