spring:
  application:
    name: content-service

server:
   port: 8022         # 指定该实例的端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 2
 
 #配置Hystrix的超时时间为15秒，解决Feign/Ribbon第一次请求失败的问题
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000   