spring:
  application:
    name: eureka-service

server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false    #是否将自己注册到Eureka Server，因为当前应用就是Eureka Server，所以设置为false
    fetchRegistry: false         #是否从Eureka Server获取注册信息，因为为单点，所以设置为false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/     #设置与Eureka Server交互的地址，多个地址之间逗号分割
  instance:
    hostname: localhost    # 指定该Eureka实例的主机名

