spring:
  application:
    name: eureka-service
  profiles:
    active: dev
server:
  port: 46960                    # 指定该Eureka实例的端口
#日志配置
logging:
  config: classpath:logback-spring.xml


--- # 开发环境**********************************************************************************************************
spring:
  profiles: dev

eureka:
  environment: ${spring.profiles}
  client:
    service-url:
      default-zone: http://10.193.17.84:${server.port}/eureka/   #设置与Eureka Server交互的地址，多个地址之间逗号分割
    registerWithEureka: true    #是否将自己注册到Eureka Server，因为当前应用就是Eureka Server，所以设置为false
    fetchRegistry: true         #是否从Eureka Server获取注册信息，因为为单点，所以设置为false
  instance:
    hostname: localhost    # 指定该Eureka实例的主机名
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true        # 设置微服务调用地址为IP优先（缺省为false）
    leaseRenewalIntervalInSeconds: 10
  server:
    enable-self-preservation: false # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 9000000

--- # 测试环境**********************************************************************************************************
spring:
  profiles: test

eureka:
  environment: ${spring.profiles}
  client:
    registerWithEureka: true    #是否将自己注册到Eureka Server，因为当前应用就是Eureka Server，所以设置为false
    fetchRegistry: true         #是否从Eureka Server获取注册信息，因为为单点，所以设置为false
    serviceUrl:
      defaultZone: http://10.193.17.86:${server.port}/eureka/,http://10.193.17.84:${server.port}/eureka/ #设置与Eureka Server交互的地址，多个地址之间逗号分割
  instance:
    hostname: eureka-server   # 指定该Eureka实例的主机名
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true        # 设置微服务调用地址为IP优先（缺省为false）
    leaseRenewalIntervalInSeconds: 10
  server:
    enable-self-preservation: false # 设为false，关闭自我保护


--- # 生产环境**********************************************************************************************************
spring:
  profiles: prd
eureka:
  environment: ${spring.profiles}
  client:
    registerWithEureka: true    #是否将自己注册到Eureka Server，因为当前应用就是Eureka Server，所以设置为false
    fetchRegistry: true         #是否从Eureka Server获取注册信息，因为为单点，所以设置为false
    serviceUrl:
      defaultZone: http://10.150.9.20:${server.port}/eureka/,http://10.150.9.21:${server.port}/eureka/  #设置与Eureka Server交互的地址，多个地址之间逗号分割
  instance:
    hostname: eureka-server    # 指定该Eureka实例的主机名
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true        # 设置微服务调用地址为IP优先（缺省为false）
    leaseRenewalIntervalInSeconds: 10
  server:
    enable-self-preservation: true # 设为false，关闭自我保护