spring:
  application:
    name: eureka-service
---
Spring:
  profiles: peer1
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: password123       # 配置登录的密码是password123
server:
  port: 8761         # 指定该实例的端口
eureka:
  instance:
    hostname: peer1    # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer2:8762/eureka/
    #registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    #fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server

---
spring:
  profiles: peer2
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: password123       # 配置登录的密码是password123
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/
