spring:
  application:
    name: config-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
    username: resdb
    password: resdb
    type: com.alibaba.druid.pool.DruidDataSource

server:
   port: 8060         # 指定该实例的端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    prefer-ip-address: true     #表示将ip注册到Eureka server
    hostname: localhost    # 指定该Eureka实例的主机名
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 2

#mybatis相关配置
mybatis:
    type-aliases-package: com.cupdata.commons.model
    mapper-locations: classpath:mapper/*.xml
    
logging:
  
  level:  # 日志级别
    
    org.springframework.web: DEBUG # 配置spring web日志级别
  
    