spring:
  application:
    name: config-service
  profiles:
    active: dev
server:
   port: 46966         # 指定该实例的端口
#日志配置
logging:
  config: classpath:logback-spring.xml

#mybatis相关配置
mybatis:
    type-aliases-package: com.cupdata.commons.model
    mapper-locations: classpath:mapper/*.xml

jasypt:
  encryptor:
    password: cupdata

--- # 开发环境**********************************************************************************************************
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
    username: resdb
    password: ENC(LwpHSjmwXgVYHjU1M9aZuA==)
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    healthcheck:
          enabled: true
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ipAddress}:46960/eureka/   #设置与Eureka Server交互的地址，多个地址之间逗号分割
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true     #表示将ip注册到Eureka server

logging:
  level: debug

--- # 测试环境**********************************************************************************************************
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.249:3306/cupdresdb?useUnicode=true&characterEncoding=UTF-8
    username: resdb
    password: ENC(LwpHSjmwXgVYHjU1M9aZuA==)
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.193.17.84:46960/eureka/,http://10.193.17.86:46960/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true        # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 20 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60 # 发呆时间，即服务续约到期时间（缺省为90s）


--- # 生产环境**********************************************************************************************************
spring:
  profiles: prd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.150.9.22:3306/sip?useUnicode=true&characterEncoding=UTF-8
    username: sip
    password: ENC(7eaGzJhB0t+ZjmzjELKw0QjoNwE573Mr)
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.150.9.20:46960/eureka/,http://10.150.9.21:46960/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}        # 将Instance ID设置成IP:端口的形式
    prefer-ip-address: true        # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 20 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60 # 发呆时间，即服务续约到期时间（缺省为90s）